version: 1.0.{build}-{branch}

branches:
  except:
    - gh-pages
    - master

skip_tags: true

skip_commits:
  files:
    - .azure-pipelines.yml
    - .github/**
    - .travis.yml
    - docs/**
    - src/**/*_posix.*
    - src/**/*_linux.*
    - src/**/*_x11.*
    - src/**/*_gtk.*
    - LICENSE
    - README.md

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2019

install:
  - xb setup

build_script:
  - xb build --config=Release --target=src\xenia-app --target=src\xenia-vfs-dump

after_build:
  - |
      7z a xenia_canary.zip          ".\build\bin\Windows\Release\xenia_canary.exe"   ".\build\bin\Windows\Release\xenia_canary.pdb"   LICENSE
      7z a xenia-vfs-dump_canary.zip ".\build\bin\Windows\Release\xenia-vfs-dump.exe" ".\build\bin\Windows\Release\xenia-vfs-dump.pdb" LICENSE

artifacts:
  - path: '*.zip'
