version: 1.0.{build}-{branch}

clone_depth: 1

matrix:
  fast_finish: true

branches:
  except:
    - gh-pages

skip_tags: true

skip_commits:
  files:
    - docs/*
    - .github/*
    - LICENSE
    - README.md
    - .azure-pipelines.yml
    - .travis.yml

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

os: Visual Studio 2019

init:
  - git config --global core.autocrlf input

install:
  - xb setup

build_script:
  - xb build --target=src\xenia-app --target=tests\xenia-cpu-ppc-tests --target=src\xenia-vfs-dump

after_build:
  - |-
      cd build\bin\Windows\Release
      7z a ..\..\..\..\xenia-%appveyor_repo_branch%.zip ..\..\..\..\LICENSE xenia.exe
      7z a ..\..\..\..\xenia-vfs-dump-%appveyor_repo_branch%.zip ..\..\..\..\LICENSE xenia-vfs-dump.exe
      cd ..\..\..\..

before_test:
  - xb gentests

test_script:
  - xb test --no_build

artifacts:
  - path: xenia-cpu-ppc-test.log
  - path: xenia-$(appveyor_repo_branch).zip
  - path: xenia-vfs-dump-$(appveyor_repo_branch).zip

deploy: off
