version: 1.0.{build}-{branch}

branches:
  except:
    - gh-pages
    - master

skip_tags: true

skip_commits:
  files:
    - docs/*
    - docs/*/*
    - .github/*
    - .github/*/*
    - LICENSE
    - README.md
    - .azure-pipelines.yml
    - .travis.yml

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019

install:
  - xb setup

build_script:
  - xb build --target=src\xenia-app --target=src\xenia-vfs-dump

after_build:
  - |-
      cd build\bin\Windows\Release
      7z a ..\..\..\..\xenia-%appveyor_repo_branch%.zip ..\..\..\..\LICENSE xenia-canary.exe
      7z a ..\..\..\..\xenia-vfs-dump-%appveyor_repo_branch%.zip ..\..\..\..\LICENSE xenia-vfs-dump.exe
      cd ..\..\..\..

test: off

artifacts:
  - path: '*.zip'

deploy: off
